services:

   project_template_back:
     image: project_template_back:latest
     container_name: "project_template"
     build:
       context: .
       dockerfile: Dockerfile
       target: development
     volumes:
       - .:/app
       - ~/.ssh:/root/.ssh
       - /root/config
     ports:
       - "8000:8000"
     depends_on:
       - project_template_db
     restart: always
     networks:
       - "project_template_network"

   project_template_db:
    container_name: "project_template_db"
    image: postgres:latest
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    env_file:
      - .env
    networks:
      - "project_template_network"

   project_template_pgadmin:
    container_name: "project_template_pgadmin"
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - project_template_db
    restart: always
    env_file:
      - .env
    networks:
      - "project_template_network"

volumes:
  postgres_data:

networks:
  project_template_network:
    driver: bridge